### ISSUE TITLE
Amethyst buff?

### ISSUE THREAD

**Issue by socalledtheraven** [Benjamin-Norton/BetterTrims#3]
Right now 1 extra second seems like a really small effect, especially considering the speed from redstone.

**Comment by Benjamin-Norton** [comment]
So with amethyst, a full set makes potions last on average 25% longer or 25% shorter. This applies to all potion effects currently affecting the player. It is possible to change the percentage in the mod config but I think the default % is ok as is.

**Comment by Benjamin-Norton** [comment]
Actually, to be more precise it's about a 33%/20% increase/decrease as each second added can also have the effect applied and when a second is removed there are fewer seconds to apply the effect. 

See [Markov Chains](https://en.wikipedia.org/wiki/Markov_chain) for why. 

Thus, increasing the default % will increase the duration exponentially. Doubling the Amethyst % to 12.5% per piece would make positive potion effects last twice as long due to the aforementioned model and negative potions would only last 66% as long.

**Comment by socalledtheraven** [comment]
Oh okay! You might want to update your readme. Maybe from "Amethyst: 6.25% chance per piece per second to reduce the duration of a negative potion effect by 1 second, or increase the duration of a positive potion effect by 1 second." to 
"Amethyst: 6.25% chance per piece to reduce the duration of a negative potion effect by 6.25%, or increase the duration of a positive potion effect by 6.25%."

**Comment by Benjamin-Norton** [comment]
The readme is accurate to what is happening, that percentage you mentioned "duration of a negative potion effect by 6.25%" changes every second it applies so that won't work.
